import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/MyProfile.jpg";

import Image from "next/image";
import web1 from "../public/web1.jpg";
import web2 from "../public/web2.jpg";
import web3 from "../public/web3.jpg";


import About from "../components/About";
import Skills from "../components/Skills";

import Navbar from "../components/Navbar";
import Link from "next/link";
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>My Portofolio | SovTech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <br></br>
      <br></br> <br></br>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">SovTech</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              I am Damilare Johnson Oloko
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              A Software Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Am a Software developer with Strong passion coding web development
              has been one of favourite by create web application diving into
              mobile app dev as well.. Join me down below and let's get
              cracking!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillTwitterCircle />
              <Link href="https://www.linkedin.com/in/damilare-johnson-oloko-92b75121b/">
                <AiFillLinkedin />
              </Link>
              <AiFillYoutube />
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        

        <About/>
        <br></br>
        <br></br>

        <Skills/>
      

        <section className="py-10">
          <div id="portfolio">
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a Software designer and
              developer, I've done a web application for companies
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including logo design,
              programming and web application.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover hover:opacity-10"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
              <b>WHS, Whatshappenning sir is a multivendor e-commerse website developed with HTML,CSS,JAVASCRIPT, AJAX, PHP, SQL, JQuery</b>
              <span className="text-teal-500"><Link href="http://whatshappeningsir.co.za/">Visit Here</Link> </span>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover hover:opacity-10"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
               <b>AWACC is a medical aids research website</b>
              <span className="text-teal-500"><Link href="https://awacc.org/">Visit Here</Link> </span>
            </div>

            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-xl hover:opacity-10"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
              <b>Group project :Attendance Fingerprint Authentication System, for capturing employee fingerprint attendance, developed with C#, Esp32, arduino IDE, C++, MySQL.</b>
              <span className="text-teal-500"><Link href="https://github.com/Tech-Army-Shared/TechArmy">Visit Here</Link> </span>
            </div>
          
         
          </div>
        </section>
      </main>
      <footer >
        <a
          href="https://www.sovtech.co.za/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright 2022{' '}
          <span >
            <Image className="img" src="/Sovtech-Logo-01.png" alt="SovTech" width="75" height="16"/>
          </span>
        </a>
      </footer>
    </div>
    
  );
}
